config/routes.rb
Rails.application.routes.draw do
  root 'index#home'

  namespace :profile do
    get :index
  end

  namespace :analysis do
    get :required_time
  end

  resources :tips do
    patch 'delete', :on => :member
  end

  resources :blogs do
    patch 'delete', :on => :member
  end

  resources :tip_genres

  namespace :manage do
    get :table_list
    get :column_list
  end

  namespace :sns do
    get :index
    get :show_tweet
    get :show_instagram
  end

  get 'admin_login/' => 'admin_login#index'
  post 'admin_login/login' => 'admin_login#login'
  post 'admin_login/logout' => 'admin_login#logout'
end

app/models/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id          :integer          not null, primary key
#  title       :text(65535)
#  body        :text(65535)
#  delete_flag :boolean          default(FALSE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  image       :string(255)
#

class Blog < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  
  attr_accessor :delete_flag_check
  
  has_one :work
  accepts_nested_attributes_for :work
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %w(edit update delete)
  
  def index
    @q = Blog.ransack(params[:q])
    blogs = @q.result
    
    # "削除されたBlogを表示しない"にチェックが入っている場合(or 'q'がnilの場合)
    if params[:q].nil? || params[:q][:delete_flag_check] == 'true'
      blogs = blogs.where(delete_flag: false)
    end
  
    # 作業時間のチェック
    if !params[:q].nil? && !params[:q][:work][:condition].empty? && !params[:q][:work][:required_time_form].empty?
      if params[:q][:work][:condition] == '1'
        ids = Work.where(required_time: params[:q][:work][:required_time_form]).select(:blog_id)
      elsif params[:q][:work][:condition] == '2'
        ids = Work.where("required_time > ?", params[:q][:work][:required_time_form]).select(:blog_id)
      elsif params[:q][:work][:condition] == '3'
        ids = Work.where("required_time < ?", params[:q][:work][:required_time_form]).select(:blog_id)
      end
      blogs = blogs.where(id: ids)
    end
    
    @works = Work.all
    @blogs = blogs.page(params[:page]).order(created_at: :desc)
  end
  
  def new
    @blog = Blog.new
    @blog.build_work
  end
  
  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blogs_path
    else
      render 'new'
    end
  end
  
  def show
    @blog = Blog.find(params[:id])
  end
  
  def edit
  end
  
  def update
    if @blog.update(update_blog_params)
      redirect_to blogs_path
    else
      render 'edit'
    end
  end
  
  def delete
    if @blog.update_attribute(:delete_flag, true)
      redirect_to blogs_path
    else
      redirect_to blogs_path, alert: '削除に失敗しました'
    end
  end
  
  private

    def blog_params
      params.require(:blog).permit(:title, :body, :image, :image_cache, :remove_image, work_attributes: [:required_time])
    end
    
    def update_blog_params
      params.require(:blog).permit(:title, :body, :image, :image_cache, :remove_image, work_attributes: [:required_time, :id])
    end
    
    def set_blog
        @blog = Blog.find(params[:id])
    end
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <%= f.label :title, "タイトル"%>
  <%= f.text_field :title, class: 'form-control' %>

  <%= f.label :body, "本文"%>
  <%= f.text_area :body, class: 'form-control', size: "100x10" %>
  
  <%= f.fields_for :work do |w| %>
    <%= w.label :required_time, "作業時間" %>
    <%= w.number_field :required_time, class: 'form-control' %>
  <% end %>
  
  <% if @blog.image? %>
    <div class="thumbnail">
      <%= image_tag @blog.image.url %>
    </div>
  <% end %><br>
  <%= f.label :image, "画像" %><br>
  <%= f.file_field :image %>
  <%= f.hidden_field :image_cache %>
  
  <% if @blog.persisted? && @blog.image? %>
    <br>
    <label>
      <%= f.check_box :remove_image %>
      画像を削除
    </label>
    <br>
  <% end %>

  <%= f.submit "登録", class: "btn btn-primary" %>
  <%= link_to "戻る", blogs_path, class: "btn btn-default" %>
<% end %>

app/views/blogs/edit.html.erb
<% provide(:title, '変更(blog)') %>
<div class="container">
  <div class="new">
    <h1>編集画面</h1>
    
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/blogs/index.html.erb
<% provide(:title, 'Blog一覧') %>
<div class="container">
  <h1>Blog一覧</h1>
  
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="panel-title">検索</div>
    </div>
    <div class="panel-body">
      <%= search_form_for @q do |f| %>
        <div class="row">
          <div class="col-sm-6">
            <div class="form-group">
              <%= f.label :title_cont, "タイトル" %>
              <%= f.text_field :title_cont, class: "form-control"%>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="form-group">
              <%= f.label :body_cont, "本文" %>
              <%= f.text_field :body_cont, class: "form-control"%>
            </div>
          </div>
          <div class="col-sm-12">
            <div class="form-inline">
              <%= f.label :created_at, "作成日" %>
              <%= f.date_select :created_at_gt, {include_blank: true, use_month_numbers: true, date_separator: ' / '}, class: "form-control" %>〜
              <%= f.date_select :created_at_lt, {include_blank: true, use_month_numbers: true, date_separator: ' / '}, class: "form-control" %>
            </div>
          </div>
          <%= f.fields_for :work do |w| %>
            <div class="col-sm-12">
              <div class="form-inline">
                <br>
                <%= w.label :required_time_form, "作業時間" %>
                <%= w.number_field :required_time_form, class: "form-control" %>
                <%= w.select :condition, [["=", 1], [">", 2], ["<", 3]], :include_blank => true %>
              </div>
            </div>
          <% end %>
          <div class="col-sm-12">
            <div class="form-inline">
              <br>
              <%= f.label :delete_flag_check, "削除されたBlogを表示しない" %>
              <%= f.check_box :delete_flag_check, {:checked => true}, true, false %>
            </div>
          </div>
        </div>
        <%= f.submit '検索', class: "btn btn-primary" %>
        <%= link_to 'クリア', blogs_path, class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
  
  <%= link_to "新規登録", new_blog_path, class: "btn btn-primary" %><br>
  
  <%= page_entries_info @blogs %><br><%= paginate @blogs %>
  <div class="row">
    <table class="table table-bordered table-striped">
      <tr>
        <th width="30%">タイトル</th>
        <th width="50%">本文</th>
        <th width="5%">作業<br>時間</th>
        <th width="10%">作成日</th>
        <th width="5%">詳細<br>変更<br>削除</th>
      </tr>
      <% @blogs.each do |blog| %>
        <tr>
          <td>
            <% if blog.persisted? && blog.image? %>
              <strong><%= blog.title %></strong>
            <% else %>
              <%= blog.title %>
            <% end %>
          </td>
          <td><%= markdown(blog.body).html_safe %></td>
          <% if !@works.find_by(blog_id: blog.id).nil? %>
            <td><%= @works.find_by(blog_id: blog.id).required_time %></td>
          <% else %>
            <td></td>
          <% end %>
          <td><%= blog.created_at.year %>年<%= blog.created_at.month %>月<%= blog.created_at.day %>日</td>
          <td>
            <%= link_to "詳細", blog_path(blog) %><br>
            <%= link_to "変更", edit_blog_path(blog) %><br>
            <%= link_to "削除", delete_blog_path(blog), :method => 'patch', data: {confirm: "本当に削除しますか？"}%>
        </tr>
      <% end %>
    </table>
  </div>
  
  <br><%= paginate @blogs %>
</div>

app/views/blogs/new.html.erb
<% provide(:title, '新規登録(blog)') %>
<div class="container">
  <div class="new">
    <h1>新規登録</h1>
    
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<% provide(:title, 'ブログ詳細') %>
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h2 class="show-title"><%= @blog.title %></h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="show-body">
        <%= markdown(@blog.body).html_safe %>
        <% if @blog.persisted? && @blog.image? %>
          <div class="show-image">
            <%= image_tag(@blog.image.url, :class => "blog-image", :align => "center") %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  
  <div><%= link_to "Blog一覧", blogs_path %></div>
</div>