config/routes.rb
Rails.application.routes.draw do
  root 'index#home'

  namespace :profile do
    get :index
  end

  namespace :analysis do
    get :required_time
  end

  resources :tips do
    patch 'delete', :on => :member
  end

  resources :blogs do
    patch 'delete', :on => :member
  end

  resources :tip_genres

  namespace :manage do
    get :table_list
    get :column_list
  end

  namespace :sns do
    get :index
    get :show_tweet
    get :show_instagram
  end

  get 'admin_login/' => 'admin_login#index'
  post 'admin_login/login' => 'admin_login#login'
  post 'admin_login/logout' => 'admin_login#logout'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "HOME", root_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <div class="text-white">
      <% if logged_in? %>
        <%= button_to 'Logout', admin_login_logout_path, class: 'btn btn-warning logout-button' %>
      <% end %>
      <h1 class="text-center">Rails開発日記</h1>
    </div>
    <nav>
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "HOME", root_path %></li>
        <li><%= link_to "BLOG", blogs_path %></li>
        <li><%= link_to "PROFILE", profile_index_path %></li>
        <%#
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">ANALYSIS<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "作業時間解析", analysis_required_time_path </li>
          </ul>
        </li>
        %>
        <li><%= link_to "TIPS", tip_genres_path %></li>
        <% if logged_in? %>
          <li><%= link_to "TABLES", manage_table_list_path %></li>
          <li><%= link_to "SNS", sns_index_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag '//www.google.com/jsapi', 'chartkick' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>